### ISSUE TITLE
app.configure is not a function

### ISSUE THREAD

**Issue by simerjit-fwrk** [jaredhanson/connect-flash#36]
Getting issue app.configure is not a function

**Comment by ToToSe** [comment]
@simerjit-fwrk app.configure is deprecated in express 4

**Comment by pratiknkulkarni** [comment]
The below configuration would work

```
var app = express();
var flash = require('connect-flash');

app.use(flash());
```

Also, might want to have a look this link: 
https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#appconfigure

**Comment by Manish270698** [comment]
@praaatik I used your suggested way but now i am getting the following deprecation warnings when i start the server:
`Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated undefined resave option; provide resave option at app.js:31:9
Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:31:9
Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated req.secret; provide secret option at app.js:31:9
Server started successfully
`

**Comment by Manish270698** [comment]
@praaatik I used your suggested way but now i am getting the following deprecation warnings when i start the server:
`Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated undefined resave option; provide resave option at app.js:31:9
Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:31:9
Mon, 24 Aug 2020 14:49:48 GMT express-session deprecated req.secret; provide secret option at app.js:31:9
Server started successfully
`
